import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <main className="flex flex-row overflow-auto bg-gray-50 w-full">
          {/* <SideNavbar /> */}
          <div className="flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
